from __future__ import annotations

from datetime import datetime, timedelta

from .base import BaseScraper, ScrapedEvent


class SampleHongKongScraper(BaseScraper):
    """
    Seed/demo scraper so the app is usable before real sources are plugged in.
    Replace this with source-specific scrapers for Time Out HK, ticketing platforms,
    clubs, venue websites, and RSS/event APIs.
    """

    source_name = "sample"

    def fetch(self) -> list[ScrapedEvent]:
        now = datetime.utcnow().replace(minute=0, second=0, microsecond=0)
        return [
            # Music events
            ScrapedEvent(
                external_id="sample-lan-kwai-fong-dj-night",
                name="Lan Kwai Fong DJ Night",
                description="Live DJ sets with happy hour specials in Central. Featuring local and international DJs.",
                source_name=self.source_name,
                organizer="LKF Collective",
                location_name="Lan Kwai Fong",
                location_address="Central, Hong Kong",
                map_url="https://maps.google.com/?q=Lan+Kwai+Fong+Hong+Kong",
                start_time_utc=now + timedelta(days=2, hours=12),
                end_time_utc=now + timedelta(days=2, hours=16),
                ticket_url="https://example.com/tickets/dj-night",
                discount_text="20% early bird until midnight",
                discount_url="https://example.com/discounts/dj-night",
            ),
            ScrapedEvent(
                external_id="sample-jazz-club-live",
                name="Blue Note Jazz Night",
                description="Evening of smooth jazz with international artists at the iconic Blue Note venue.",
                source_name=self.source_name,
                organizer="Blue Note Hong Kong",
                location_name="Blue Note Hong Kong",
                location_address="Central, Hong Kong",
                map_url="https://maps.google.com/?q=Blue+Note+Hong+Kong",
                start_time_utc=now + timedelta(days=5, hours=19),
                end_time_utc=now + timedelta(days=5, hours=22),
                ticket_url="https://example.com/tickets/jazz",
                discount_text="",
                discount_url="",
            ),
            # Sports events
            ScrapedEvent(
                external_id="sample-hk-marathon-training",
                name="Victoria Harbour Run Club",
                description="Community sports training session with pacing groups for all levels.",
                source_name=self.source_name,
                organizer="HK Run Club",
                location_name="Tsim Sha Tsui Promenade",
                location_address="Kowloon, Hong Kong",
                map_url="https://maps.google.com/?q=Tsim+Sha+Tsui+Promenade",
                start_time_utc=now + timedelta(days=3, hours=4),
                end_time_utc=now + timedelta(days=3, hours=6),
                ticket_url="https://example.com/register/run-club",
                discount_text="",
                discount_url="",
            ),
            ScrapedEvent(
                external_id="sample-basketball-tournament",
                name="3x3 Basketball Tournament",
                description="Weekend basketball tournament open to all skill levels with prizes.",
                source_name=self.source_name,
                organizer="HK Basketball Association",
                location_name="Victoria Park",
                location_address="Causeway Bay, Hong Kong",
                map_url="https://maps.google.com/?q=Victoria+Park+Hong+Kong",
                start_time_utc=now + timedelta(days=7, hours=10),
                end_time_utc=now + timedelta(days=7, hours=18),
                ticket_url="https://example.com/register/basketball",
                discount_text="",
                discount_url="",
            ),
            # Food & Drink events
            ScrapedEvent(
                external_id="sample-wine-tasting",
                name="French Wine Tasting Evening",
                description="Sample premium French wines paired with artisan cheese and charcuterie.",
                source_name=self.source_name,
                organizer="Wine Society HK",
                location_name="IFC Mall",
                location_address="Central, Hong Kong",
                map_url="https://maps.google.com/?q=IFC+Mall+Hong+Kong",
                start_time_utc=now + timedelta(days=4, hours=18),
                end_time_utc=now + timedelta(days=4, hours=21),
                ticket_url="https://example.com/tickets/wine-tasting",
                discount_text="10% off for members",
                discount_url="https://example.com/discounts/wine",
            ),
            ScrapedEvent(
                external_id="sample-food-festival",
                name="Hong Kong Street Food Festival",
                description="Explore the best of Hong Kong street food from local vendors.",
                source_name=self.source_name,
                organizer="HK Food Association",
                location_name="Temple Street Night Market",
                location_address="Yau Ma Tei, Kowloon",
                map_url="https://maps.google.com/?q=Temple+Street+Night+Market",
                start_time_utc=now + timedelta(days=6, hours=17),
                end_time_utc=now + timedelta(days=6, hours=23),
                ticket_url="",
                discount_text="",
                discount_url="",
            ),
            # Culture events
            ScrapedEvent(
                external_id="sample-art-exhibition",
                name="Contemporary Art Exhibition",
                description="Featuring works by emerging Asian artists exploring themes of identity and migration.",
                source_name=self.source_name,
                organizer="Hong Kong Arts Centre",
                location_name="Hong Kong Arts Centre",
                location_address="Wan Chai, Hong Kong",
                map_url="https://maps.google.com/?q=Hong+Kong+Arts+Centre",
                start_time_utc=now + timedelta(days=1, hours=10),
                end_time_utc=now + timedelta(days=1, hours=20),
                ticket_url="https://example.com/tickets/art-exhibition",
                discount_text="Free admission on Wednesdays",
                discount_url="",
            ),
            ScrapedEvent(
                external_id="sample-chinese-opera",
                name="Traditional Chinese Opera Performance",
                description="Classic Cantonese opera performance with elaborate costumes and makeup.",
                source_name=self.source_name,
                organizer="Hong Kong Cultural Centre",
                location_name="Hong Kong Cultural Centre",
                location_address="Tsim Sha Tsui, Hong Kong",
                map_url="https://maps.google.com/?q=Hong+Kong+Cultural+Centre",
                start_time_utc=now + timedelta(days=8, hours=19),
                end_time_utc=now + timedelta(days=8, hours=22),
                ticket_url="https://example.com/tickets/opera",
                discount_text="",
                discount_url="",
            ),
            # Networking events
            ScrapedEvent(
                external_id="sample-tech-meetup",
                name="Startup Founders Networking Night",
                description="Connect with fellow entrepreneurs and investors in Hong Kong's tech scene.",
                source_name=self.source_name,
                organizer="HK Startup Association",
                location_name="The Hub",
                location_address="Wan Chai, Hong Kong",
                map_url="https://maps.google.com/?q=The+Hub+Hong+Kong",
                start_time_utc=now + timedelta(days=4, hours=18),
                end_time_utc=now + timedelta(days=4, hours=21),
                ticket_url="https://example.com/register/tech-meetup",
                discount_text="",
                discount_url="",
            ),
            ScrapedEvent(
                external_id="sample-expats-mingle",
                name="Expats Mingle @ Sky Lounge",
                description="Monthly networking event for expats living in Hong Kong.",
                source_name=self.source_name,
                organizer="InterNations Hong Kong",
                location_name="Sky Lounge",
                location_address="Central, Hong Kong",
                map_url="https://maps.google.com/?q=Sky+Lounge+Central+Hong+Kong",
                start_time_utc=now + timedelta(days=9, hours=19),
                end_time_utc=now + timedelta(days=9, hours=23),
                ticket_url="https://example.com/register/expats",
                discount_text="",
                discount_url="",
            ),
            # Party events
            ScrapedEvent(
                external_id="sample-rooftop-party",
                name="Rooftop Party with Live DJ",
                description="Infinity pool party with DJ sets and cocktail specials overlooking the skyline.",
                source_name=self.source_name,
                organizer="Club HK",
                location_name="W Hotel",
                location_address="West Kowloon, Hong Kong",
                map_url="https://maps.google.com/?q=W+Hotel+Hong+Kong",
                start_time_utc=now + timedelta(days=10, hours=20),
                end_time_utc=now + timedelta(days=11, hours=2),
                ticket_url="https://example.com/tickets/rooftop",
                discount_text="2-for-1 drinks before 10pm",
                discount_url="https://example.com/discounts/rooftop",
            ),
            ScrapedEvent(
                external_id="sample-henley-regatta",
                name="Hong Kong Regatta",
                description="Annual rowing competition with food vendors and family activities.",
                source_name=self.source_name,
                organizer="Hong Kong Rowing Association",
                location_name="Sai Kung",
                location_address="Sai Kung, New Territories",
                map_url="https://maps.google.com/?q=Sai+Kung+Hong+Kong",
                start_time_utc=now + timedelta(days=12, hours=8),
                end_time_utc=now + timedelta(days=12, hours=17),
                ticket_url="",
                discount_text="",
                discount_url="",
            ),
        ]
